movie/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='setadmin'

urlpatterns = [
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('addmovie/', views.AddMovies.as_view(), name='addmovie'),
    path('setmovie/', views.SetMovies.as_view(), name='setmovie'),
    path('', views.LoiginAdmin.as_view(), name='adminlogin'),
    path('logout/', views.adminLogout, name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie_user/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name='user_side'

urlpatterns = [
    path('dashboard/', views.UserDashboard.as_view(), name='dashboard'),
    path('booktickets/', views.BookTickets.as_view(), name='booktickets'),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('selectseats/<int:pk>', views.BuyTicket.as_view(), name='selectseats'),
    path('history/', views.BookHistory.as_view(), name='bookhistory'),
    path('download/', views.DownloadTicket.as_view(), name='download'),
    path('ticket/<int:pk>', views.Ticket.as_view(), name ='ticket')
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('movie.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('movie_user.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class AdminSide(models.Model):
    username = models.CharField(max_length=25)
    password = models.CharField(max_length=16)



class MovieMaster(models.Model):
    m_name = models.CharField('Movie Name',max_length=50)
    m_desc = models.CharField('Movie Description', max_length=250)
    m_image = models.ImageField('Movie Image',upload_to="pics/")

    class Meta:
        unique_together = ["m_name", "m_desc", "m_image",]

    def get_absolute_url(self):
        return reverse("setadmin:addmovie")

    def __str__(self):
        return self.m_name


class SetMovie(models.Model):
    active = models.ForeignKey(MovieMaster, on_delete=models.CASCADE)
    show = models.CharField('Show Time', max_length=50)
    start_time = models.DateField()
    end_time = models.DateField()
    price = models.IntegerField()
    seats = models.CharField(max_length=100, default="")

    class Meta:
        unique_together = ["active", "show", "start_time", "end_time"]

    def get_absolute_url(self):
        return reverse("setadmin:setmovie")

movie/forms.py
from django import forms
from . import models



class AddMovieForm(forms.ModelForm):
    class Meta:
        model = models.MovieMaster
        fields = ('m_name', 'm_desc', 'm_image')

        widgets = {
            'm_name': forms.TextInput(attrs={'class': 'form-control'}),
            'm_desc': forms.TextInput(attrs={'class': 'form-control'}),
            # 'm_image': forms.FileInput(attrs={'class': 'form-control'}),
        }

class SetMovieForm(forms.ModelForm):

    # movie_choice = models.MovieMaster.objects.filter(setmovie__isnull=False)

    class Meta:
        model = models.SetMovie
        fields = ('active' ,'start_time', 'end_time', 'show', 'price')
        movie_choice = models.MovieMaster.objects.filter(setmovie__isnull=True)

        widgets = {
            'active': forms.Select(choices=movie_choice,attrs={'class': 'form-control', 'style':'width:300px'}),
            'show':forms.Select(choices=(("1", "Morning"),("2", "AfterNoon"),("3", "Evening"),("4", "Night")) ,attrs={'class': 'form-control', 'style':'width:300px'}),
            'start_time': forms.DateInput(attrs={'class': 'form-control', 'id':'datepicker', 'style':'width:140px;'}),
            'end_time': forms.DateInput(attrs={'class': 'form-control', 'id':'datepicker1', 'style':'width:140px;'}), 
            'price': forms.NumberInput(attrs={'class': 'form-control', 'style':'width:140px;'})      
        }

movie/views.py
from django.shortcuts import render, redirect
from django.views import generic
from . import models
from .models import SetMovie, MovieMaster
from . import forms
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from movie_user.models import BookedSeatsModel
from django.http import JsonResponse
# Create your views here.

############ADmin login page######################
class LoiginAdmin(View):
    template_name = "movie/admin_login.html"

    def get(self, request, *args, **kwargs):
        
        return render(request, self.template_name)

    def post(self,request, *args, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            superusers = User.objects.get(username = username)
            print("-------------------------------------")
            print(superusers.username)
            print(superusers.is_superuser)
            print("--------------------------------------")
            if superusers.is_superuser == True:
                login(request, user)
                return redirect('../dashboard/')

        else:
            return render(request, self.template_name)


def adminLogout(request):
    logout(request)
    return redirect('../login/')

#Admin dashboard page
class Dashboard(generic.ListView):
    model_add = models.MovieMaster
    model_set = models.SetMovie
    movies = MovieMaster.objects.filter(setmovie__isnull=False).distinct()
    model = MovieMaster

    template_name = "movie/dashboard.html"

    def get_context_data(self, **kwargs):
        movies = MovieMaster.objects.filter(setmovie__isnull=False).distinct()
        context = super().get_context_data(**kwargs)
        context['movies'] = movies
        return context


#This page will be used by admin for adding movies to system when then will be used for setting shows####################
class AddMovies(generic.CreateView):  
    form_class = forms.AddMovieForm
    model = models.MovieMaster
    template_name = "movie/addmovies.html"

    
#From the list of movies added admin can set show for particular movie
class SetMovies(generic.CreateView):
    form_class = forms.SetMovieForm
    model = models.SetMovie
    # context_object_name = 'movies'
    # def post(self, request, *args, **kwargs): 
    #     if request.method == 'POST':
    #         request.POST['']
    #         models.MovieGraphCount(m_name=)
    
    template_name = "movie/setmovies.html"
    

movie/templates/movie/addmovies.html
{% extends "movie/admin_base.html" %}

{% block content %}



<div class="form-group">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-success" value="submit">
    
    </form>

</div>




{% endblock %}

movie/templates/movie/admin_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
	<title>MovieWatch</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="{% static 'date/css/pikaday.css' %}">
    <link rel="stylesheet" href="{% static 'date/css/site.css' %}">
	<!-- VENDOR CSS -->
	<link rel="stylesheet" href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/linearicons/style.css' %}">
	<link rel="stylesheet" href="{% static 'assets/vendor/chartist/css/chartist-custom.css' %}">
	<!-- MAIN CSS -->
	<link rel="stylesheet" href="{% static 'assets/css/main.css' %}">
	<!-- GOOGLE FONTS -->
	<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
	<!-- ICONS -->
	<link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
</head>

<body>
	<!-- WRAPPER -->
	<div id="wrapper">
		<!-- NAVBAR -->
		<nav class="navbar navbar-default navbar-fixed-top">
			<div class="brand">
				<a href="{% url 'setadmin:dashboard' %}"><img src="{% static 'assets/img/logo-background.png' %}" alt="MovieWatch" class="img-responsive logo" style="max-width: 40px; height: 10%;"></a>
			</div>
			<div class="container-fluid">
				<div class="navbar-btn">
					<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
				</div>
				
		
				<div id="navbar-menu">
					<ul class="nav navbar-nav navbar-right">

						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="{% static 'assets/img/user.png' %}" class="img-circle" alt="Avatar"> <span>{{request.user.username}}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
							<ul class="dropdown-menu">
								<li><a href="{% url 'user_side:logout' %}"><i class="lnr lnr-exit"></i> <span>Logout</span></a></li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</nav>
		<!-- END NAVBAR -->
		<!-- LEFT SIDEBAR -->
		<div id="sidebar-nav" class="sidebar">
			<div class="sidebar-scroll">
				<nav>
					<ul class="nav">
						<li><a href="{% url 'setadmin:dashboard' %}" class="active"><i class="lnr lnr-home"></i> <span>Movie Catalogue</span></a></li>
						<li><a href="{% url 'setadmin:addmovie' %}" class=""><i class="lnr lnr-text-format"></i> <span>Add Movies</span></a></li>
						<li><a href="{% url 'setadmin:setmovie' %}" class=""><i class="lnr lnr-cog"></i> <span>Set Movie Times</span></a></li>
					</ul>
				</nav>
			</div>
		</div>
		<!-- END LEFT SIDEBAR -->
		<!-- MAIN -->
		<div class="main">
			<!-- MAIN CONTENT -->

				<div class="container-fluid">
					<br>
					<!-- OVERVIEW -->

					<!-- END OVERVIEW -->
					<!-- ---------------------------------------------------------------------------------- -->
					{% block content %}


					{% endblock %}

			<!-- ------------------------------------------------ -->
				</div>
			</div>
			<!-- END MAIN CONTENT -->
		</div>
		<!-- END MAIN -->
		<div class="clearfix"></div>
		<footer>
			<div class="container-fluid">
				<p class="copyright">&copy; 2022. All Rights Reserved.</p>
			</div>
		</footer>
	</div>
	<!-- END WRAPPER -->
	<!-- Javascript -->
	<script src="{% static 'date/moment.js' %}"></script>
<script src="{% static 'date/pikaday.js' %}"></script>
<script>
    var picker = new Pikaday({
        field: document.getElementById('datepicker'),
        format: 'YYYY-MM-DD',
        onSelect: function() {
            console.log(this.getMoment().format('YYYY-MM-DD'));
        }
    });
</script>

<script>
	var picker = new Pikaday({
		field: document.getElementById('datepicker1'),
		format: 'YYYY-MM-DD',
		onSelect: function () {
			console.log(this.getMoment().format('YYYY-MM-DD'));
			theme: 'dark-theme'
		}
	});
</script>
	<script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
	<script src="{% static 'assets/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'assets/vendor/chartist/js/chartist.min.js' %}"></script>
	<script src="{% static 'assets/scripts/klorofil-common.js' %}"></script>
	<script>
	$(function() {
		var data, options;

		// headline charts
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[23, 29, 24, 40, 25, 24, 35],
				[14, 25, 18, 34, 29, 38, 44],
			]
		};

		options = {
			height: 300,
			showArea: true,
			showLine: false,
			showPoint: false,
			fullWidth: true,
			axisX: {
				showGrid: false
			},
			lineSmooth: false,
		};

		new Chartist.Line('#headline-chart', data, options);


		// visits trend charts
		data = {
			labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
			series: [{
				name: 'series-real',
				data: [200, 380, 350, 320, 410, 450, 570, 400, 555, 620, 750, 900],
			}, {
				name: 'series-projection',
				data: [240, 350, 360, 380, 400, 450, 480, 523, 555, 600, 700, 800],
			}]
		};

		options = {
			fullWidth: true,
			lineSmooth: false,
			height: "270px",
			low: 0,
			high: 'auto',
			series: {
				'series-projection': {
					showArea: true,
					showPoint: false,
					showLine: false
				},
			},
			axisX: {
				showGrid: false,

			},
			axisY: {
				showGrid: false,
				onlyInteger: true,
				offset: 0,
			},
			chartPadding: {
				left: 20,
				right: 20
			}
		};

		new Chartist.Line('#visits-trends-chart', data, options);


		// visits chart
		data = {
			labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
			series: [
				[6384, 6342, 5437, 2764, 3958, 5068, 7654]
			]
		};

		options = {
			height: 300,
			axisX: {
				showGrid: false
			},
		};

		new Chartist.Bar('#visits-chart', data, options);


		// real-time pie chart
		var sysLoad = $('#system-load').easyPieChart({
			size: 130,
			barColor: function(percent) {
				return "rgb(" + Math.round(200 * percent / 100) + ", " + Math.round(200 * (1.1 - percent / 100)) + ", 0)";
			},
			trackColor: 'rgba(245, 245, 245, 0.8)',
			scaleColor: false,
			lineWidth: 5,
			lineCap: "square",
			animate: 800
		});

		var updateInterval = 3000; // in milliseconds

		setInterval(function() {
			var randomVal;
			randomVal = getRandomInt(0, 100);

			sysLoad.data('easyPieChart').update(randomVal);
			sysLoad.find('.percent').text(randomVal);
		}, updateInterval);

		function getRandomInt(min, max) {
			return Math.floor(Math.random() * (max - min + 1)) + min;
		}

	});
	</script>
</body>

</html>

movie/templates/movie/admin_login.html
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </head>

    <body style="background-color:rgb(37, 37, 37)">
        <br>
        <br>
        <br>

        <div class="container">
            <div class="container">
                <div class="container">
                    <!-- <img src="{% static 'logo.jpg'%}" style="height: 80px; width: 80px;" alt=""> -->
                    
                    <div class="jumbotron" style="width: 40%; margin-left: 32%; background-color:white">
                        <h2 style=" font-style:oblique; margin-left: 26%;">Admin Login</h2>
                        <br>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                              <label for="exampleInputEmail1">Username:</label>
                              <input type="text" class="form-control" id="exampleInputEmail1" name="username"  placeholder="Enter username">
                             </small>
                            </div>
                            <div class="form-group">
                              <label for="exampleInputPassword1">Password</label>
                              <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password">
                            </div>
                            <br>
                            <button type="submit" class="btn btn-primary" style="width: 100%;">Submit</button>
                          </form>
                          <a href="{% url 'user_side:login' %}" style="margin-left: 42%; ">User login</a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

movie/templates/movie/chart.html
{% extends "movie/admin_base.html" %}
{% load static %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<script>

    $(function () {

      var $populationChart = $("#population-chart");
      $.ajax({
        url: $populationChart.data("url"),
        success: function (data) {

          var ctx = $populationChart[0].getContext("2d");

          new Chart(ctx, {
            type: 'bar',
            data: {
              labels: data.labels,
              datasets: [{
                label: 'Population',
                backgroundColor: 'blue',
                data: data.data
              }]          
            },
            options: {
              responsive: true,
              legend: {
                position: 'top',
              },
              title: {
                display: true,
                text: 'Population Bar Chart'
              }
            }
          });

        }
      });

    });

  </script>

{% endblock %}

movie/templates/movie/dashboard.html
{% extends "movie/admin_base.html" %}

{% block content %}

{% for movie in movies %}

<img src="{{movie.m_image.url}}" alt="" style="height: 450px; width: 400px; ">


{% endfor %}

{% endblock %}

movie/templates/movie/setmovies.html
{% extends "movie/admin_base.html" %}
{% load static %}
{% block content %}



<div class="form-group">
    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        {{form.as_p}}

        <input type="submit" class="btn btn-success" value="submit" width="300px">
    
    </form>

</div>




{% endblock %}